### ISSUE TITLE
Minecraft 1.12.2 crash on MCinaBox

### ISSUE THREAD

**Issue by Happ1ness-dev** [DaMatrix/ForgeRocks#4]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FP2MixinLoader (fp2-0.0.1.728-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/30/22 5:06 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ForgeRocks (forgerocks)
Caused by: java.lang.RuntimeException: Unable to load rocksdb native libraries!
	at net.daporkchop.forgerocks.ForgeRocks1_12.preInit(ForgeRocks1_12.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
	at net.daporkchop.forgerocks.ForgeRocks1_12.preInit(ForgeRocks1_12.java:36)
	... 41 more
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared library
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:73)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
	... 42 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2063)
	at java.io.File.createTempFile(File.java:2109)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:132)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
	... 43 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version 4.19.113-perf-gf346e5f286af
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 530695688 bytes (506 MB) / 827326464 bytes (789 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4096m -Xms128m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                           | Signature                                |
	|:----- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCH   | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| LCH   | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| LCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge      | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCE   | forgerocks | 7.3.1-1.12.2 | ForgeRocks-7.3.1-1.12.2-full.jar | None                                     |
	| LC    | fp2        | 0.0.1.728    | fp2-0.0.1.728-1.12.2.jar         | None                                     |

	Loaded coremods (and transformers): 
FP2MixinLoader (fp2-0.0.1.728-1.12.2.jar)
  
```

Here's also the log file, if needed.
[latest.log](https://github.com/DaMatrix/ForgeRocks/files/9225327/latest.log)

My device is Poco F3 (SD870) 8/256, running on Android 11.
MCinaBox version is 0.1.4-p5.

**Comment by DaMatrix** [comment]
android launchers have a tendency of not properly supporting many basic features, such as (in this case) creating a temporary file. there's nothing i can do to work around this, this is something MCinaBox would need to fix.
